# Generated by Django 4.1 on 2022-10-07 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepExercise',
            fields=[
                ('pk_id', models.AutoField(db_column='pk_id', primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, db_column='content', max_length=200, null=True)),
                ('ex1', models.CharField(blank=True, db_column='ex1', max_length=150, null=True)),
                ('ex2', models.CharField(blank=True, db_column='ex2', max_length=150, null=True)),
                ('ex3', models.CharField(blank=True, db_column='ex3', max_length=150, null=True)),
                ('ex4', models.CharField(blank=True, db_column='ex4', max_length=150, null=True)),
                ('session_number', models.IntegerField(blank=True, db_column='session_number', null=True)),
                ('answer', models.IntegerField(blank=True, db_column='answer', null=True)),
            ],
            options={
                'db_table': 'deep_exercise',
            },
        ),
        migrations.CreateModel(
            name='SimilarFileUpload',
            fields=[
                ('pk_id', models.AutoField(db_column='PK_ID', primary_key=True, serialize=False)),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_route', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
