# Generated by Django 4.1 on 2022-10-07 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PREVIOUS_EXERCISE_EXAM',
            fields=[
                ('PK_ID', models.AutoField(db_column='PK_ID', primary_key=True, serialize=False)),
                ('PRE_EXAM_NUM', models.IntegerField(blank=True, null=True)),
                ('PRE_EXAM_SUBSTANCE', models.CharField(blank=True, max_length=100, null=True)),
                ('PRE_EXAM_FIGURE', models.IntegerField(blank=True, null=True)),
                ('FK_PREVIOUS_EXERCISE_QUES', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'previous_exercise_exam',
            },
        ),
        migrations.CreateModel(
            name='PREVIOUS_EXERCISE_EXAM_ANSWER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SELECT', models.IntegerField(blank=True, null=True)),
                ('DIVISION', models.IntegerField(blank=True, null=True)),
                ('QUE_NUM', models.IntegerField(blank=True, null=True)),
                ('QUE_ID', models.IntegerField(blank=True, null=True)),
                ('USER_ID', models.CharField(blank=True, max_length=30, null=True)),
                ('ANSWER_NUM', models.IntegerField(blank=True, null=True)),
                ('ANSWER_CHECK', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'previous_exercise_exam_answer',
            },
        ),
        migrations.CreateModel(
            name='PREVIOUS_EXERCISE_EXAM_RESULT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SELECT', models.IntegerField(blank=True, null=True)),
                ('DIVISION', models.IntegerField(blank=True, null=True)),
                ('USER_ID', models.CharField(blank=True, max_length=30, null=True)),
                ('QUE_COUNT', models.IntegerField(blank=True, null=True)),
                ('ANSWER_COUNT', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'previous_exercise_exam_result',
            },
        ),
        migrations.CreateModel(
            name='PREVIOUS_EXERCISE_FIGURE_TABLE',
            fields=[
                ('PK_ID', models.AutoField(db_column='PK_ID', primary_key=True, serialize=False)),
                ('PRE_EXE_FIG_TAB_FIGURE', models.CharField(blank=True, max_length=100, null=True)),
                ('PRE_EXE_FIG_TAB_FIGURE_PATH', models.CharField(blank=True, db_column='PRE_EXE_FIG_TAB_FIGURE_PATH', max_length=300, null=True)),
                ('FK_PREVIOUS_EXERCISE_QUES', models.IntegerField(blank=True, db_column='FK_PREVIOUS_EXERCISE_QUES', null=True)),
                ('FK_PREVIOUS_EXERCISE_EXAM', models.IntegerField(blank=True, db_column='FK_PREVIOUS_EXERCISE_EXAM', null=True)),
            ],
            options={
                'db_table': 'previous_exercise_figure_table',
            },
        ),
        migrations.CreateModel(
            name='PREVIOUS_EXERCISE_SUMMARY',
            fields=[
                ('PK_ID', models.AutoField(db_column='PK_ID', primary_key=True, serialize=False)),
                ('PRE_EXE_CLASS', models.IntegerField(blank=True, db_column='PRE_EXE_CLASS', null=True)),
                ('PRE_EXE_YEAR', models.IntegerField(blank=True, db_column='PRE_EXE_YEAR', null=True)),
                ('PRE_EXE_NUMBER', models.IntegerField(blank=True, db_column='PRE_EXE_NUMBER', null=True)),
                ('PRE_EXE_SUBJECT', models.IntegerField(blank=True, db_column='PRE_EXE_SUBJECT', null=True)),
            ],
            options={
                'db_table': 'previous_exercise_summary',
            },
        ),
        migrations.CreateModel(
            name='PREVIOUS_EXERCISE_QUES',
            fields=[
                ('PK_ID', models.AutoField(db_column='PK_ID', primary_key=True, serialize=False)),
                ('PRE_EXE_QUES_NUM', models.IntegerField(blank=True, null=True)),
                ('PRE_EXE_QUES_DIFFICULTY', models.CharField(blank=True, max_length=2, null=True)),
                ('PRE_EXE_QUES_QUESTION', models.CharField(blank=True, max_length=500, null=True)),
                ('PRE_EXE_QUES_FIGURE', models.IntegerField(blank=True, null=True)),
                ('FK_PREVIOUS_EXERCISE_SUMMARY', models.IntegerField(blank=True, null=True)),
                ('ANSWER_RATE', models.IntegerField(default=0)),
                ('ANSWER', models.ForeignKey(blank=True, db_column='ANSWER', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='extest.previous_exercise_exam')),
            ],
            options={
                'db_table': 'previous_exercise_ques',
            },
        ),
    ]
