# Generated by Django 4.1.2 on 2022-11-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.IntegerField(blank=True, null=True)),
                ('feb', models.IntegerField(blank=True, null=True)),
                ('mar', models.IntegerField(blank=True, null=True)),
                ('apr', models.IntegerField(blank=True, null=True)),
                ('may', models.IntegerField(blank=True, null=True)),
                ('jun', models.IntegerField(blank=True, null=True)),
                ('jul', models.IntegerField(blank=True, null=True)),
                ('aug', models.IntegerField(blank=True, null=True)),
                ('sept', models.IntegerField(blank=True, null=True)),
                ('oct', models.IntegerField(blank=True, null=True)),
                ('nov', models.IntegerField(blank=True, null=True)),
                ('dec', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MonthScore',
            },
        ),
        migrations.CreateModel(
            name='WeekScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.IntegerField(blank=True, null=True)),
                ('tue', models.IntegerField(blank=True, null=True)),
                ('wed', models.IntegerField(blank=True, null=True)),
                ('thu', models.IntegerField(blank=True, null=True)),
                ('fri', models.IntegerField(blank=True, null=True)),
                ('sat', models.IntegerField(blank=True, null=True)),
                ('sun', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WeekScore',
            },
        ),
    ]
