# Generated by Django 4.1 on 2022-10-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_community_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
