# Generated by Django 4.1.2 on 2022-11-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_community_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('pk_id', models.AutoField(db_column='PK_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('job', models.CharField(blank=True, max_length=10, null=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
