# Generated by Django 4.1.2 on 2022-11-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='src',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
