# Generated by Django 4.1 on 2022-10-07 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('pk_id', models.AutoField(db_column='PK_ID', primary_key=True, serialize=False)),
                ('page_subject1', models.IntegerField(blank=True, default=1, null=True)),
                ('page_subject2', models.IntegerField(blank=True, default=1, null=True)),
                ('page_subject3', models.IntegerField(blank=True, default=1, null=True)),
                ('page_subject4', models.IntegerField(blank=True, default=1, null=True)),
                ('page_subject5', models.IntegerField(blank=True, default=1, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('pk_id', models.AutoField(db_column='PK_ID', primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('page', models.IntegerField(blank=True, default=1, null=True)),
                ('subject', models.IntegerField(blank=True, null=True)),
                ('dib', models.IntegerField(blank=True, default=0, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
