# Generated by Django 4.1 on 2022-10-07 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_sum_detail1',
            fields=[
                ('pk_id', models.AutoField(db_column='PK_ID', primary_key=True, serialize=False)),
                ('job', models.CharField(blank=True, db_column='JOB', max_length=50, null=True)),
            ],
            options={
                'db_table': 'data_sum_detail1',
            },
        ),
        migrations.CreateModel(
            name='License_raking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Technology_other',
            fields=[
                ('pk_id', models.AutoField(db_column='PK_ID', primary_key=True, serialize=False)),
                ('qual', models.CharField(blank=True, db_column='QUAL', max_length=50, null=True)),
                ('summary', models.CharField(blank=True, db_column='SUMMARY', max_length=1000, null=True)),
                ('fk_detail1', models.ForeignKey(blank=True, db_column='FK_DETAIL1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='search.data_sum_detail1')),
            ],
            options={
                'db_table': 'technology_other',
            },
        ),
        migrations.CreateModel(
            name='Technology_korea',
            fields=[
                ('pk_id', models.AutoField(db_column='PK_ID', primary_key=True, serialize=False)),
                ('qual', models.CharField(blank=True, db_column='QUAL', max_length=50, null=True)),
                ('summary', models.CharField(blank=True, db_column='SUMMARY', max_length=1000, null=True)),
                ('fk_detail1', models.ForeignKey(blank=True, db_column='FK_DETAIL1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='search.data_sum_detail1')),
            ],
            options={
                'db_table': 'technology_korea',
            },
        ),
    ]
