# Generated by Django 4.1 on 2022-10-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_rename_qual_technology_korea_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology_korea',
            name='activate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='technology_other',
            name='activate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
