# Generated by Django 4.1.2 on 2022-11-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_technology_korea_activate_technology_other_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology_korea',
            name='summary',
            field=models.CharField(blank=True, db_column='SUMMARY', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='technology_other',
            name='summary',
            field=models.CharField(blank=True, db_column='SUMMARY', max_length=10000, null=True),
        ),
    ]
